services:
  anycast_server:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 3

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - anycast_server